# Introducción a Numpy

In [1]:
import sys
import numpy as np

Numpy proporciona un nuevo contenedor de datos a Python, los `ndarray`s, además de funcionalidad especializada para poder manipularlos de forma eficiente.

Hablar de manipulación de datos en Python es sinónimo de Numpy y prácticamente todo el ecosistema científico de Python está construido sobre Numpy. Digamos que Numpy es el ladrillo que ha permitido levantar edificios tan sólidos como Pandas, Matplotlib, Scipy, scikit-learn,...

**Índice**

* [¿Por qué un nuevo contenedor de datos?](#%C2%BFPor-qu%C3%A9-un-nuevo-contenedor-de-datos?)
* [Tipos de datos](#Tipos-de-datos)
* [Creación de `numpy` arrays](#Creaci%C3%B3n-de-numpy-arrays)
* [Operaciones disponibles más típicas](#Operaciones-disponibles-m%C3%A1s-t%C3%ADpicas)
* [Metadatos y anatomía de un `ndarray`](#Metadatos-y-anatom%C3%ADa-de-un-ndarray)
* [Indexación](#Indexaci%C3%B3n)
* [Manejo de valores especiales](#Manejo-de-valores-especiales)
* [Subarrays, vistas y copias](#Subarrays,-vistas-y-copias)
* [¿Cómo funcionan los ejes de un `ndarray`?](#%C2%BFC%C3%B3mo-funcionan-los-ejes-en-un-ndarray?)
* [Reformateo de `ndarray`s](#Reformateo-de-ndarrays)
* [Broadcasting](#Broadcasting)


* [`ndarrays` estructurados y `recarray`s](#ndarrays-estructurados-y-recarrays)
* [Concatenación y partición de `ndarray`s](#Concatenaci%C3%B3n-y-partici%C3%B3n-de-ndarrays)
* [Funciones matemáticas, funciones universales *ufuncs* y vectorización](#Funciones-matem%C3%A1ticas,-funciones-universales-ufuncs-y-vectorizaci%C3%B3n)
* [Estadística](#Estad%C3%ADstica)
* [Ordenando, buscando y contando](#Ordenando,-buscando-y-contando)
* [Polinomios](#Polinomios)
* [Álgebra lineal](#%C3%81lgebra-lineal)
* [Manipulación de `ndarray`s](#Manipulaci%C3%B3n-de-ndarrays)
* [Módulos de interés dentro de numpy](#M%C3%B3dulos-de-inter%C3%A9s-dentro-de-numpy)
* [Cálculo matricial](#C%C3%A1lculo-matricial)

## ¿Por qué un nuevo contenedor de datos?

En Python, disponemos, de partida, de diversos contenedores de datos, listas, tuplas, diccionarios, conjuntos,..., ¿por qué añadir uno más?.

¡Por conveniencia!, a pesar de la pérdida de flexibilidad. Es una solución de compromiso.

* Uso de memoria más eficiente: Por ejemplo, una lista puede contener distintos tipos de objetos lo que provoca que Python deba guardar información del tipo de cada elemento contenido en la lista. Por otra parte, un `ndarray` contiene tipos homogéneos, es decir, todos los elementos son del mismo tipo, por lo que la información del tipo solo debe guardarse una vez independientemente del número de elementos que tenga el `ndarray`.


![arrays_vs_listas](./images/numpy_tutorial/03_01_array_vs_list.png)
***(imagen por Jake VanderPlas y extraída [de GitHub](https://github.com/jakevdp/PythonDataScienceHandbook)).***

* Más rápido: Por ejemplo, en una lista que consta de elementos con diferentes tipos Python debe realizar trabajos extra para saber si los tipos son compatibles con las operaciones que estamos realizando. Cuando trabajamos con un `ndarray` ya podemos saber eso de partida y podemos tener operaciones más eficientes (además de que mucha funcionalidad está programada en C, C++, Cython, Fortran).


* Operaciones vectorizadas


* Funcionalidad extra: Muchas operaciones de álgebra lineal, transformadas rápidas de Fourier, estadística básica, histogramas,...


* Acceso a los elementos más conveniente: Indexación más avanzada que con los tipos normales de Python


* ...

Uso de memoria

In [3]:
# AVISO: SYS.GETSYZEOF NO ES FIABLE

lista = list(range(5_000_000))
arr = np.array(lista, dtype=np.uint32)
print("5 millones de elementos")
print(sys.getsizeof(lista))
print(sys.getsizeof(arr))

print()

lista = list(range(100))
arr = np.array(lista, dtype=np.uint8)
print("100 elementos")
print(sys.getsizeof(lista))
print(sys.getsizeof(arr))

5 millones de elementos
40000056
20000112

100 elementos
856
212


Velocidad de operaciones

In [4]:
a = list(range(1000000))
%timeit sum(a)
print(sum(a))

4.32 ms ± 26.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
499999500000


In [5]:
a = np.array(a)
%timeit np.sum(a)
print(np.sum(a))

99.4 µs ± 1.37 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
499999500000


Operaciones vectorizadas

In [6]:
# Suma de dos vectores elemento a elemento
a = [1, 1, 1]
b = [3, 4, 3]
print(a + b)
print("Fail")

[1, 1, 1, 3, 4, 3]
Fail


In [7]:
# Suma de dos vectores elemento a elemento
a = np.array([1, 1, 1])
b = np.array([3, 4, 3])
print(a + b)
print("\o/")

[4 5 4]
\o/


Funcionalidad más conveniente

In [8]:
# suma acumulada
a = list(range(100))
print([sum(a[: i + 1]) for i in a])

a = np.array(a)
print(a.cumsum())

[0, 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66, 78, 91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325, 351, 378, 406, 435, 465, 496, 528, 561, 595, 630, 666, 703, 741, 780, 820, 861, 903, 946, 990, 1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485, 1540, 1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145, 2211, 2278, 2346, 2415, 2485, 2556, 2628, 2701, 2775, 2850, 2926, 3003, 3081, 3160, 3240, 3321, 3403, 3486, 3570, 3655, 3741, 3828, 3916, 4005, 4095, 4186, 4278, 4371, 4465, 4560, 4656, 4753, 4851, 4950]
[   0    1    3    6   10   15   21   28   36   45   55   66   78   91
  105  120  136  153  171  190  210  231  253  276  300  325  351  378
  406  435  465  496  528  561  595  630  666  703  741  780  820  861
  903  946  990 1035 1081 1128 1176 1225 1275 1326 1378 1431 1485 1540
 1596 1653 1711 1770 1830 1891 1953 2016 2080 2145 2211 2278 2346 2415
 2485 2556 2628 2701 2775 2850 2926 3003 3081 3160 3240 3321 3403 3486
 3570 3655 3741 3828 3916 4005 4095 

Acceso a elementos más conveniente

In [9]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
print("acceso a la primera fila: ", a[0])
print("acceso a la primera columna: ", a[:][0], " Fail!!!")

acceso a la primera fila:  [11, 12, 13]
acceso a la primera columna:  [11, 12, 13]  Fail!!!


In [10]:
a = np.array(a)
print("acceso a la primera fila: ", a[0])
print("acceso a la primera columna: ", a[:, 0], " \o/")

acceso a la primera fila:  [11 12 13]
acceso a la primera columna:  [11 21 31]  \o/


...

Recapitulando un poco.

***Los `ndarray`s son contenedores multidimensionales, homogéneos con elementos de tamaño fijo, de dimensión predefinida.***

## Tipos de datos

Como los arrays deben ser homogéneos tenemos tipos de datos. Algunos de ellos se pueden ver en la siguiente tabla:

| Data type	    | Descripción |
|---------------|-------------|
| ``bool_``     | Booleano (True o False) almacenado como un Byte |
| ``int_``      | El tipo entero por defecto (igual que el `long` de C; normalmente será `int64` o `int32`)| 
| ``intc``      | Idéntico al ``int`` de C (normalmente `int32` o `int64`)| 
| ``intp``      | Entero usado para indexación (igual que `ssize_t` en C; normalmente `int32` o `int64`)| 
| ``int8``      | Byte (de -128 a 127)| 
| ``int16``     | Entero (de -32768 a 32767)|
| ``int32``     | Entero (de -2147483648 a 2147483647)|
| ``int64``     | Entero (de -9223372036854775808 a 9223372036854775807)| 
| ``uint8``     | Entero sin signo (de 0 a 255)| 
| ``uint16``    | Entero sin signo (de 0 a 65535)| 
| ``uint32``    | Entero sin signo (de 0 a 4294967295)| 
| ``uint64``    | Entero sin signo (de 0 a 18446744073709551615)| 
| ``float_``    | Atajo para ``float64``.| 
| ``float16``   | Half precision float: un bit para el signo, 5 bits para el exponente, 10 bits para la mantissa| 
| ``float32``   | Single precision float: un bit para el signo, 8 bits para el exponente, 23 bits para la mantissa|
| ``float64``   | Double precision float: un bit para el signo, 11 bits para el exponente, 52 bits para la mantissa|
| ``complex_``  | Atajo para `complex128`.| 
| ``complex64`` | Número complejo, represantedo por dos *floats* de 32-bits| 
| ``complex128``| Número complejo, represantedo por dos *floats* de 64-bits| 

Es posible tener una especificación de tipos más detallada, pudiendo especificar números con *big endian* o *little endian*. No vamos a ver esto en este momento.

El tipo por defecto que usa `numpy` al crear un *ndarray* es `np.float_`, siempre que no específiquemos explícitamente el tipo a usar.

Por ejemplo, un array de tipo `np.uint8` puede tener los siguientes valores:

In [11]:
import itertools

for i, bits in enumerate(itertools.product((0, 1), repeat=8)):
    print(i, bits)

0 (0, 0, 0, 0, 0, 0, 0, 0)
1 (0, 0, 0, 0, 0, 0, 0, 1)
2 (0, 0, 0, 0, 0, 0, 1, 0)
3 (0, 0, 0, 0, 0, 0, 1, 1)
4 (0, 0, 0, 0, 0, 1, 0, 0)
5 (0, 0, 0, 0, 0, 1, 0, 1)
6 (0, 0, 0, 0, 0, 1, 1, 0)
7 (0, 0, 0, 0, 0, 1, 1, 1)
8 (0, 0, 0, 0, 1, 0, 0, 0)
9 (0, 0, 0, 0, 1, 0, 0, 1)
10 (0, 0, 0, 0, 1, 0, 1, 0)
11 (0, 0, 0, 0, 1, 0, 1, 1)
12 (0, 0, 0, 0, 1, 1, 0, 0)
13 (0, 0, 0, 0, 1, 1, 0, 1)
14 (0, 0, 0, 0, 1, 1, 1, 0)
15 (0, 0, 0, 0, 1, 1, 1, 1)
16 (0, 0, 0, 1, 0, 0, 0, 0)
17 (0, 0, 0, 1, 0, 0, 0, 1)
18 (0, 0, 0, 1, 0, 0, 1, 0)
19 (0, 0, 0, 1, 0, 0, 1, 1)
20 (0, 0, 0, 1, 0, 1, 0, 0)
21 (0, 0, 0, 1, 0, 1, 0, 1)
22 (0, 0, 0, 1, 0, 1, 1, 0)
23 (0, 0, 0, 1, 0, 1, 1, 1)
24 (0, 0, 0, 1, 1, 0, 0, 0)
25 (0, 0, 0, 1, 1, 0, 0, 1)
26 (0, 0, 0, 1, 1, 0, 1, 0)
27 (0, 0, 0, 1, 1, 0, 1, 1)
28 (0, 0, 0, 1, 1, 1, 0, 0)
29 (0, 0, 0, 1, 1, 1, 0, 1)
30 (0, 0, 0, 1, 1, 1, 1, 0)
31 (0, 0, 0, 1, 1, 1, 1, 1)
32 (0, 0, 1, 0, 0, 0, 0, 0)
33 (0, 0, 1, 0, 0, 0, 0, 1)
34 (0, 0, 1, 0, 0, 0, 1, 0)
35 (0, 0, 1, 0, 0, 0, 1, 1)
36

Es decir, puede contener valores que van de 0 a 255 ($2^8$).

¿Cuántos bytes tendrá un `ndarray` de 10 elementos cuyo tipo de datos es un `np.int8`?

In [12]:
a = np.arange(10, dtype=np.int8)
print(a.nbytes)
print(sys.getsizeof(a))

10
122


In [13]:
a = np.repeat(1, 100000).astype(np.int8)
print(a.nbytes)
print(sys.getsizeof(a))

100000
100112


## Creación de numpy arrays

Podemos crear numpy arrays de muchas formas.

* Rangos numéricos

`np.arange`, `np.linspace`, `np.logspace`

* Datos homogéneos

`np.zeros`, `np.ones`

* Elementos diagonales

`np.diag`, `np.eye`

* A partir de otras estructuras de datos ya creadas

`np.array`

* A partir de otros numpy arrays

`np.empty_like`

* A partir de ficheros

`np.loadtxt`, `np.genfromtxt`,...


* A partir de un escalar

`np.full`, `np.tile`,...

* A partir de valores aleatorios

`np.random.randint`, `np.random.randint`, `np.random.randn`,...

...

In [14]:
a = np.arange(10)  # similar a range pero devuelve un ndarray en lugar de un objeto range
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a = np.linspace(0, 1, 101)
print(a)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


In [16]:
a_i = np.zeros((2, 3), dtype=np.int)
a_f = np.zeros((2, 3))
print(a_i)
print(a_f)

[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]


/tmp/ipykernel_111074/1555057317.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a_i = np.zeros((2, 3), dtype=np.int)


In [17]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
a = np.array(((1, 2, 3, 4, 5, 6), (10, 20, 30, 40, 50, 60)), dtype=np.float)
print(a)

[[ 1.  2.  3.  4.  5.  6.]
 [10. 20. 30. 40. 50. 60.]]


/tmp/ipykernel_111074/3205374155.py:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.float


In [19]:
np.full((5, 5), -999)

array([[-999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999],
       [-999, -999, -999, -999, -999]])

In [20]:
np.random.randint(0, 50, 15)

array([ 0, 33, 45, 48, 46, 44,  6, 27, 44,  7, 24, 46, 46,  0, 44])

<div class="alert alert-success">
    <p>Referencias:</p>
    <p><a href="https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation">array creation</a></p>
    <p><a href="https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html#routines-array-creation">routines for array creation</a></p>
</div>

**Practicando**

Recordad que siempre podéis usar `help`, `?`, `np.lookfor`,..., para obtener más información.

In [21]:
help(np.sum)

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 

In [22]:
?np.rad2deg

Call signature:  np.rad2deg(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'rad2deg'>
File:            ~/miniconda3/envs/algebra/lib/python3.9/site-packages/numpy/__init__.py
Docstring:      
rad2deg(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Convert angles from radians to degrees.

Parameters
----------
x : array_like
    Angle in radians.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original val

In [23]:
np.lookfor("create array")

Search results for 'create array'
---------------------------------
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.char.array
    Create a `chararray`.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.from_dlpack
    Create a NumPy array from an object implementing the ``__dlpack__``
numpy.rec.fromarrays
    Create a record array from a (flat) list of arrays
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.rec.fromfile
    Create an array from binary file data
numpy.rec.fromstring
    Create a record array from binary data
numpy.lib.Arrayterator
    Buffered iterator for big 

Ved un poco como funciona `np.repeat`, `np.empty_like`,... 

In [24]:
# Play area

In [25]:
%load ../../solutions/03_01_np_array_creacion.py

ValueError: '../../solutions/03_01_np_array_creacion.py' was not found in history, as a file, url, nor in the user namespace.

## Operaciones disponibles más típicas

In [ ]:
a = np.random.rand(5, 2)
print(a)

In [ ]:
a.sum()

In [ ]:
a.sum(axis=0)

In [ ]:
a.sum(axis=1)

In [ ]:
a.ravel()

In [ ]:
a.reshape(2, 5)

In [ ]:
a.T

In [ ]:
a.transpose()

In [ ]:
a.mean()

In [ ]:
a.mean(axis=1)

In [ ]:
a.cumsum(axis=1)

<div class="alert alert-success">
    <p>Referencias:</p>
    <p><a href="https://docs.scipy.org/doc/numpy/user/quickstart.html">Quick start tutorial</a></p>
</div>

**Practicando**

Mirad más métodos de un `ndarray` y toquetead. Si no entendéis algo, preguntad:

In [ ]:
dir(a)

In [ ]:
# Play area

In [ ]:
%load ../../solutions/03_02_np_operaciones_tipicas.py

## Metadatos y anatomía de un `ndarray`

En realidad, un `ndarray` es un bloque de memoria con información extra sobre como interpretar su contenido. La memoria dinámica (RAM) se puede considerar como un 'churro' lineal y es por ello que necesitamos esa información extra para saber como formar ese `ndarray`, sobre todo la información de `shape` y `strides`.

Esta parte va a ser un poco más esotérica para los no iniciados pero considero que es necesaria para poder entender mejor nuestra nueva estructura de datos y poder sacarle mejor partido.

In [ ]:
a = np.random.randn(5000, 5000)

El número de dimensiones del `ndarray`

In [ ]:
a.ndim

El número de elementos en cada una de las dimensiones

In [ ]:
a.shape

El número de elementos

In [ ]:
a.size

El tipo de datos de los elementos

In [ ]:
a.dtype

El número de bytes de cada elemento

In [ ]:
a.itemsize

El número de bytes que ocupa el `ndarray` (es lo mismo que `size` por `itemsize`)

In [ ]:
a.nbytes

El *buffer* que contiene los elementos del `ndarray`

In [ ]:
a.data

Pasos a dar en cada dimensión cuando nos movemos entre elementos

In [ ]:
a.strides

![strides](./images/numpy_tutorial/03_02_strides.svg)
***(imagen extraída [de GitHub](https://github.com/btel/2016-erlangen-euroscipy-advanced-numpy)).***

Más cosas

In [ ]:
a.flags

Pequeño ejercicio, ¿por qué tarda menos en sumar elementos en una dimensión que en otra si es un array regular?

In [ ]:
%timeit a.sum(axis=0)
%timeit a.sum(axis=1)

Pequeño ejercicio, ¿por qué ahora el resultado es diferente?

In [ ]:
aT = a.T
%timeit aT.sum(axis=0)
%timeit aT.sum(axis=1)

In [ ]:
print(aT.strides)
print(aT.flags)

In [ ]:
print(np.repeat((1, 2, 3), 3))
print()
a = np.repeat((1, 2, 3), 3).reshape(3, 3)
print(a)
print()
print(a.sum(axis=0))
print()
print(a.sum(axis=1))

<div class="alert alert-success">
    <p>Referencias:</p>
    <p><a href="https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#internal-memory-layout-of-an-ndarray">Internal memory layout of an ndarray</a></p>
    <p><a href="https://docs.scipy.org/doc/numpy/reference/internals.html#multidimensional-array-indexing-order-issues">multidimensional array indexing order issues</a></p>
</div>

## Indexación

Si ya has trabajado con indexación en estructuras de Python, como listas, tuplas o strings, la indexación en Numpy te resultará muy familiar. 

Por ejemplo, por hacer las cosas sencillas, vamos a crear un `ndarray` de 1D:

In [ ]:
a = np.arange(10, dtype=np.uint8)
print(a)

In [ ]:
print(a[:])  # para acceder a todos los elementos
print(a[:-1])  # todos los elementos menos el último
print(a[1:])  # todos los elementos menos el primero
print(a[::2])  # el primer, el tercer, el quinto,..., elemento
print(a[3])  # el cuarto elemento
print(a[-1:-5:-1])  # ¿?

In [ ]:
# Practicad vosotros

Para *ndarrays* de una dimensión es exactamente igual que si usásemos listas o tuplas de Python:

* Primer elemento tiene índice 0
* Los índices negativos empiezan a contar desde el final
* slices/rebanadas con `[start:stop:step]`

Con un `ndarray` de más dimensiones las cosas ya cambian con respecto a Python puro:

In [ ]:
a = np.random.randn(10, 2)
print(a)

In [ ]:
a[1]  # ¿Qué nos dará esto?
a[
    1, 1
]  # Si queremos acceder a un elemento específico hay que dar su posición completa en el ndarray
a[::3, 1]

Si tenemos dimensiones mayores a 1 es parecido a las listas pero los índices se separan por comas para las nuevas dimensiones.
<img src="./images/numpy_tutorial/03_03_arraygraphics_0.png" width=400px />
(imagen extraída de [aquí](https://github.com/gertingold/euroscipy-numpy-tutorial))

In [ ]:
a = np.arange(40).reshape(5, 8)
print(a)

In [ ]:
a[2, -3]

Para obtener más de un elemento hacemos *slicing* para cada eje:
<img src="./images/numpy_tutorial/03_04_arraygraphics_1.png" width=400px />
(imagen extraída de [aquí](https://github.com/gertingold/euroscipy-numpy-tutorial))

In [ ]:
a[:3, :5]

¿Cómo podemos conseguir los elementos señalados en esta imagen?
<img src="./images/numpy_tutorial/03_06_arraygraphics_2_wo.png" width=400px />

(imagen extraída de [aquí](https://github.com/gertingold/euroscipy-numpy-tutorial))

In [ ]:
a[x:x, x:x]

¿Cómo podemos conseguir los elementos señalados en esta imagen?
<img src="./images/numpy_tutorial/03_08_arraygraphics_3_wo.png" width=400px />

(imagen extraída de [aquí](https://github.com/gertingold/euroscipy-numpy-tutorial))

In [ ]:
a[x:x, x:x]

¿Cómo podemos conseguir los elementos señalados en esta imagen?
<img src="./images/numpy_tutorial/03_10_arraygraphics_4_wo.png" width=400px />

(imagen extraída de [aquí](https://github.com/gertingold/euroscipy-numpy-tutorial))

In [ ]:
a[x:x, x:x]

¿Cómo podemos conseguir los elementos señalados en esta imagen?
<img src="./images/numpy_tutorial/03_12_arraygraphics_5_wo.png" width=400px />

(imagen extraída de [aquí](https://github.com/gertingold/euroscipy-numpy-tutorial))

In [ ]:
a[x:x, x:x]

Soluciones a lo anterior:

<img src="./images/numpy_tutorial/03_05_arraygraphics_2.png" width=200px />
<img src="./images/numpy_tutorial/03_07_arraygraphics_3.png" width=200px />
<img src="./images/numpy_tutorial/03_09_arraygraphics_4.png" width=200px />
<img src="./images/numpy_tutorial/03_11_arraygraphics_5.png" width=200px />

(imágenes extraídas de [aquí](https://github.com/gertingold/euroscipy-numpy-tutorial))

**Fancy indexing**

Con *fancy indexing* podemos hacer cosas tan variopintas como:

<img src="./images/numpy_tutorial/03_13_arraygraphics_6.png" width=300px />
<img src="./images/numpy_tutorial/03_14_arraygraphics_7.png" width=300px />

(imágenes extraídas de [aquí](https://github.com/gertingold/euroscipy-numpy-tutorial))

Es decir, podemos indexar usando `ndarray`s de booleanos ó usando listas de índices para extraer elementos concretos de una sola vez.

**WARNING: En el momento que usamos *fancy indexing* nos devuelve un nuevo *ndarray* que no tiene porque conservar la estructura original.**

Por ejemplo, en el siguiente caso no devuelve un *ndarray* de dos dimensiones porque la máscara no tiene porqué ser regular y, por tanto, devuelve solo los valores que cumplen el criterio en un vector (*ndarray* de una dimensión).

In [ ]:
a = np.arange(10).reshape(2, 5)
print(a)

In [ ]:
bool_indexes = a % 2 == 0
print(bool_indexes)

In [ ]:
a[bool_indexes]

Sin embargo, sí que lo podríamos usar para modificar el *ndarray* original en base a un criterio y seguir manteniendo la misma forma.

In [ ]:
a[bool_indexes] = 999
print(a)

<div class="alert alert-success">
    <p>Referencias:</p>
    <p><a href="https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#arrays-indexing">array indexing</a></p>
    <p><a href="https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#indexing-arrays">indexing arrays</a></p>
</div>

## Manejo de valores especiales

`numpy` provee de varios valores especiales: `np.nan`, `np.Inf`, `np.Infinity`, `np.inf`, `np.infty`,...

In [ ]:
a = 1 / np.arange(10)
print(a)

In [ ]:
a[0] == np.inf

In [ ]:
a.max()  # Esto no es lo que queremos

In [ ]:
a.mean()  # Esto no es lo que queremos

In [ ]:
a[np.isfinite(a)].max()

In [ ]:
a[-1] = np.nan
print(a)

In [ ]:
a.mean()

In [ ]:
np.isnan(a)

In [ ]:
np.isfinite(a)

In [ ]:
np.isinf(a)  # podéis mirar también np.isneginf, np.isposinf

`numpy` usa el estándar IEEE de números flotantes para aritmética (IEEE 754). Esto significa que *Not a
Number* no es equivalente a *infinity*. También, *positive infinity* no es equivalente a *negative infinity*. Pero *infinity* es equivalente a *positive infinity*.

In [ ]:
1 < np.inf

In [ ]:
1 < -np.inf

In [ ]:
1 > -np.inf

In [ ]:
1 == np.inf

In [ ]:
1 < np.nan

In [ ]:
1 > np.nan

In [ ]:
1 == np.nan

## Subarrays, vistas y copias

**¡IMPORTANTE!**

Vistas y copias: `numpy`, por defecto, siempre devuelve vistas para evitar incrementos innecesarios de memoria. Este comportamiento difiere del de Python puro donde una rebanada (*slicing*) de una lista devuelve una copia. Si queremos una copia de un `ndarray` debemos obtenerla de forma explícita:

In [ ]:
a = np.arange(10)
b = a[2:5]
print(a)
print(b)

In [ ]:
b[0] = 222
print(a)
print(b)

Este comportamiento por defecto es realmente muy útil, significa que, trabajando con grandes conjuntos de datos, podemos acceder y procesar piezas de estos conjuntos de datos sin necesidad de copiar el buffer de datos original.

A veces, es necesario crear una copia. Esto se puede realizar fácilmente usando el método `copy` de los *ndarrays*. El ejemplo anterior usando una copia en lugar de una vista:

In [ ]:
a = np.arange(10)
b = a[2:5].copy()
print(a)
print(b)
b[0] = 222
print(a)
print(b)

## ¿Cómo funcionan los ejes en un `ndarray`?

Por ejemplo, cuando hacemos `a.sum()`, `a.sum(axis=0)`, `a.sum(axis=1)`.

¿Qué pasa si tenemos más de dos dimensiones?

Vamos a ver ejemplos:

In [ ]:
a = np.arange(10).reshape(5, 2)

In [ ]:
a.shape

In [ ]:
a.sum()

In [ ]:
a.sum(axis=0)

In [ ]:
a.sum(axis=1)

![](./images/numpy_tutorial/03_16_ndarray_axes_2D.png)
(imagen extraída de [aquí](https://github.com/gertingold/euroscipy-numpy-tutorial))

In [ ]:
a = np.arange(9).reshape(3, 3)
print(a)
print(a.sum(axis=0))
print(a.sum(axis=1))

![](./images/numpy_tutorial/03_17_ndarray_axes_3D.png)
(imagen extraída de [aquí](https://github.com/gertingold/euroscipy-numpy-tutorial))

In [ ]:
a = np.arange(24).reshape(2, 3, 4)
print(a)
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.sum(axis=2))

Por ejemplo, en el primer caso, `axis=0`, lo que sucede es que cogemos todos los elementos del primer índice y aplicamos la operación para cada uno de los elementos de los otros dos ejes. Hecho de uno en uno sería lo siguiente:

In [ ]:
print(a[:, 0, 0].sum(), a[:, 0, 1].sum(), a[:, 0, 2].sum(), a[:, 0, 3].sum())
print(a[:, 1, 0].sum(), a[:, 1, 1].sum(), a[:, 1, 2].sum(), a[:, 1, 3].sum())
print(a[:, 2, 0].sum(), a[:, 2, 1].sum(), a[:, 2, 2].sum(), a[:, 2, 3].sum())

Sin contar el eje que estamos usando, las dimensiones que quedan son 3 x 4 (segunda y tercera dimensiones) por lo que el resultado son 12 elementos.

Para el caso de `axis=1`:

In [ ]:
print(a[0, :, 0].sum(), a[0, :, 1].sum(), a[0, :, 2].sum(), a[0, :, 3].sum())
print(a[1, :, 0].sum(), a[1, :, 1].sum(), a[1, :, 2].sum(), a[1, :, 3].sum())

Sin contar el eje que estamos usando, las dimensiones que quedan son 2 x 4 (primera y tercera dimensiones) por lo que el resultado son 8 elementos.

Para el caso de `axis=2`:

In [ ]:
print(a[0, 0, :].sum(), a[0, 1, :].sum(), a[0, 2, :].sum())
print(a[1, 0, :].sum(), a[1, 1, :].sum(), a[1, 2, :].sum())

Sin contar el eje que estamos usando, las dimensiones que quedan son 2 x 3 (primera y segunda dimensiones) por lo que el resultado son 3 elementos.

## Reformateo de `ndarray`s

Podemos cambiar la forma de los `ndarray`s usando el método `reshape`. Por ejemplo, si queremos colocar los números del 1 al 9 en un grid  $3 \times 3$ lo podemos hacer de la siguiente forma:

In [ ]:
a = np.arange(1, 10).reshape(3, 3)

Para que el cambio de forma no dé errores hemos de tener cuidado en que los tamaños del `ndarray` inicial y del `ndarray` final sean compatibles.

In [ ]:
# Por ejemplo, lo siguiente dará error?
a = np.arange(1, 10).reshape(5, 2)

Otro patrón común de cambio de forma sería la conversion de un `ndarray` de 1D en uno de 2D añadiendo un nuevo eje. Lo podemos hacer usando, nuevamente, el método `reshape` o usando `numpy.newaxis`.

In [ ]:
# Por ejemplo un array 2D de una fila
a = np.arange(3)
a1_2D = a.reshape(1, 3)
a2_2D = a[np.newaxis, :]
print(a1_2D)
print(a1_2D.shape)
print(a2_2D)
print(a2_2D.shape)

In [ ]:
# Por ejemplo un array 2D de una columna
a = np.arange(3)
a1_2D = a.reshape(3, 1)
a2_2D = a[:, np.newaxis]
print(a1_2D)
print(a1_2D.shape)
print(a2_2D)
print(a2_2D.shape)

## Broadcasting

Es poible realizar operaciones en *ndarrays* de diferentes tamaños. En algunos casos `numpy` puede transformar estos *ndarrays* automáticamente de forma que todos tienen la misma forma. Esta conversión automática se llama **broadcasting**.

Normas del Broadcasting

Para determinar la interacción entre dos `ndarray`s en Numpy se sigue un conjunto de reglas estrictas:

* Regla 1: Si dos `ndarray`s difieren en su número de dimensiones la forma de aquel con menos dimensiones se rellena con 1's a su derecha.
- Regla 2: Si la forma de dos `ndarray`s no es la misma en ninguna de sus dimensiones, el `ndarry` con forma igual a 1 en esa dimensión se 'alarga' para tener simulares dimensiones que los del otros `ndarray`.
- Regla 3: Si en cualquier dimensión el tamaño no es igual y ninguno de ellos es igual a 1 entonces obtendremos un error.

Resumiendo, cuando se opera en dos *ndarrays*, `numpy` compara sus formas (*shapes*) elemento a elemento. Empieza por las dimensiones más a la izquierda y trabaja hacia las siguientes dimensiones. Dos  dimensiones son compatibles cuando

    ambas son iguales o
    una de ellas es 1

Si estas condiciones no se cumplen se lanzará una excepción `ValueError: frames are not aligned` indicando que los *ndarrays* tienen formas incompatibles. El tamaño del *ndarray* resultante es el tamaño máximo a lo largo de cada dimensión de los *ndarrays* de partida.

De forma más gráfica:

![numpy broadcasting in 2D](./images/numpy_tutorial/03_15_numpy_broadcasting.png)
(imagen extraída de [aquí](https://github.com/btel/2016-erlangen-euroscipy-advanced-numpy))

```
a:      4 x 3     a:      4 x 3      a:      4 x 1
b:      4 x 3     b:          3      b:          3
result: 4 x 3     result: 4 x 3      result: 4 x 3
```

Intentemos reproducir los esquemas de la imagen anterior.

In [ ]:
a = np.repeat((0, 10, 20, 30), 3).reshape(4, 3)
b = np.repeat((0, 1, 2), 4).reshape(3, 4).T
print(a)
print(b)
print(a + b)

In [ ]:
a = np.repeat((0, 10, 20, 30), 3).reshape(4, 3)
b = np.array((0, 1, 2))
print(a)
print(b)
print(a + b)

In [ ]:
a = np.array((0, 10, 20, 30)).reshape(4, 1)
b = np.array((0, 1, 2))
print(a)
print(b)
print(a + b)

<div class="alert alert-success">
    <p>Referencias:</p>
    <p><a href="https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html">Basic broadcasting</a></p>
    <p><a href="http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc">Broadcasting more in depth</a></p>
</div>

## `ndarrays` estructurados y `recarray`s

Antes hemos comentado que los `ndarray`s deben ser homogéneos pero era un poco inexacto, en realidad, podemos tener `ndarray`s que tengan diferentes tipos. Estos se llaman `ndarray`s estructurados y `recarray`s.

Veamos ejemplos:

In [ ]:
nombre = ["paca", "pancracio", "nemesia", "eulogio"]
edad = [72, 68, 86, 91]
a = np.array(np.zeros(4), dtype=[("name", "<S10"), ("age", np.int)])
a["name"] = nombre
a["age"] = edad
print(a)

Podemos acceder a las columnas por nombre

In [ ]:
a["name"]

A todos los elementos menos el primero

In [ ]:
a["age"][1:]

Un `recarray` es similar pero podemos acceder a los campos con notación de punto (*dot notation*).

In [ ]:
ra = a.view(np.recarray)

In [ ]:
ra.name

Esto introduce un poco de *overhead* para acceder ya que se realizan algunas operaciones de más.

## Concatenación y partición de `ndarrays`

Podemos combinar múltiples *ndarrays* en uno o separar uno en varios.

Para concatenar podemos usar `np.concatenate`, `np.hstack`, `np.vstack`, `np.dstack`. Ejemplos:

In [ ]:
a = np.array([1, 1, 1, 1])
b = np.array([2, 2, 2, 2])

Podemos concatenar esos dos arrays usando `np.concatenate`:

In [ ]:
np.concatenate([a, b])

No solo podemos concatenar *ndarrays* de una sola dimensión:

In [ ]:
np.concatenate([a.reshape(2, 2), b.reshape(2, 2)])

Podemos elegir sobre qué eje concatenamos:

In [ ]:
np.concatenate([a.reshape(2, 2), b.reshape(2, 2)], axis=1)

Podemos concatenar más de dos arrays:

In [ ]:
c = [3, 3, 3, 3]
np.concatenate([a, b, c])

Si queremos ser más explícitos podemos usar `np.hstack` o `np.vstack`. La `h` y la `v` son para horizontal y vertical, respectivamente.

In [ ]:
np.hstack([a, b])

In [ ]:
np.vstack([a, b])

Podemos concatenar en la tercera dimensión usamos `np.dstack`.

De la misma forma que podemos concatenar, podemos partir *ndarrays* usando `np.split`, `np.hsplit`, `np.vsplit`, `np.dsplit`.

In [ ]:
# Intentamos entender como funciona la partición probando...

## Funciones matemáticas, funciones universales *ufuncs* y vectorización

¿Qué es eso de *ufunc*? 

De la [documentación oficial de Numpy](http://docs.scipy.org/doc/numpy/reference/ufuncs.html):
    
> A universal function (or ufunc for short) is a function that operates on ndarrays in an element-by-element fashion, supporting array broadcasting, type casting, and several other standard features. That is, a ufunc is a “**vectorized**” wrapper for a function that takes a **fixed number of scalar inputs** and produces a **fixed number of scalar outputs**.

Una *ufunc* es una *Universal function* o función universal que actúa sobre todos los elementos de un  `ndarray`, es decir aplica la funcionalidad sobre cada uno de los elementos del `ndarray`. Esto se conoce como vectorización.

Por ejemplo, veamos la operación de elevar al cuadrado una lista en python puro o en `numpy`:

In [ ]:
# En Python puro
a_list = list(range(10000))

%timeit [i ** 2 for i in a_list]

In [ ]:
# En numpy
an_arr = np.arange(10000)

%timeit np.power(an_arr, 2)

In [ ]:
a = np.arange(10)

np.power(a, 2)

La función anterior eleva al cuadrado cada uno de los elementos del `ndarray` anterior.

Dentro de `numpy` hay muchísimas *ufuncs* y `scipy` (no lo vamos a ver) dispone de muchas más *ufuns* mucho más especializadas.

En `numpy` tenemos, por ejemplo:

* Funciones trigonométricas: `sin`, `cos`, `tan`, `arcsin`, `arccos`, `arctan`, `hypot`, `arctan2`, `degrees`, `radians`, `unwrap`, `deg2rad`, `rad2deg`

In [ ]:
# juguemos un poco con ellas

* Funciones hiperbólicas: `sinh`, `cosh`, `tanh`, `arcsinh`, `arccosh`, `arctanh`

In [ ]:
# juguemos un poco con ellas

* Redondeo: `around`, `round_`, `rint`, `fix`, `floor`, `ceil`, `trunc`

In [ ]:
# juguemos un poco con ellas

* Sumas, productos, diferencias: `prod`, `sum`, `nansum`, `cumprod`, `cumsum`, `diff`, `ediff1d`, `gradient`, `cross`, `trapz`

In [ ]:
# juguemos un poco con ellas

* Exponentes y logaritmos: `exp`, `expm1`, `exp2`, `log`, `log10`, `log2`, `log1p`, `logaddexp`, `logaddexp2`

In [ ]:
# juguemos un poco con ellas

* Otras funciones especiales: `i0`, `sinc`

In [ ]:
# juguemos un poco con ellas

* Trabajo con decimales: `signbit`, `copysign`, `frexp`, `ldexp`

In [ ]:
# juguemos un poco con ellas

* Operaciones aritméticas: `add`, `reciprocal`, `negative`, `multiply`, `divide`, `power`, `subtract`, `true_divide`, `floor_divide`, `fmod`, `mod`, `modf`, `remainder`

In [ ]:
# juguemos un poco con ellas

* Manejo de números complejos: `angle`, `real`, `imag`, `conj`

In [ ]:
# juguemos un poco con ellas

* Miscelanea: `convolve`, `clip`, `sqrt`, `square`, `absolute`, `fabs`, `sign`, `maximum`, `minimum`, `fmax`, `fmin`, `nan_to_num`, `real_if_close`, `interp`


...

In [ ]:
# juguemos un poco con ellas

<div class="alert alert-success">
    <p>Referencias:</p>
    <p><a href="http://docs.scipy.org/doc/numpy/reference/ufuncs.html">Ufuncs</a></p>
</div>

## Estadística

* Orden: `amin`, `amax`, `nanmin`, `nanmax`, `ptp`, `percentile`, `nanpercentile`


* Medias y varianzas: `median`, `average`, `mean`, `std`, `var`, `nanmedian`, `nanmean`, `nanstd`, `nanvar`


* Correlacionando: `corrcoef`, `correlate`, `cov`


* Histogramas: `histogram`, `histogram2d`, `histogramdd`, `bincount`, `digitize`

...

In [ ]:
# juguemos un poco con ellas

## Ordenando, buscando y contando

* Ordenando: `sort`, `lexsort`, `argsort`, `ndarray.sort`, `msort`, `sort_complex`, `partition`, `argpartition`


* Buscando: `argmax`, `nanargmax`, `argmin`, `nanargmin`, `argwhere`, `nonzero`, `flatnonzero`, `where`, `searchsorted`, `extract`


* Contando: `count_nonzero`

...

In [ ]:
# juguemos un poco con ellas

## Polinomios

* Series de potencias: `numpy.polynomial.polynomial`


* Clase Polynomial: `np.polynomial.Polynomial`


* Básicos: `polyval`, `polyval2d`, `polyval3d`, `polygrid2d`, `polygrid3d`, `polyroots`, `polyfromroots`


* Ajuste: `polyfit`, `polyvander`, `polyvander2d`, `polyvander3d`


* Cálculo: `polyder`, `polyint`


* Álgebra: `polyadd`, `polysub`, `polymul`, `polymulx`, `polydiv`, `polypow`


* Miscelánea: `polycompanion`, `polydomain`, `polyzero`, `polyone`, `polyx`, `polytrim`, `polyline`


* Otras funciones polinómicas: `Chebyshev`, `Legendre`, `Laguerre`, `Hermite`

...

In [ ]:
# juguemos un poco con ellas

## Álgebra lineal

Lo siguiente que se encuentra dentro de `numpy.linalg` vendrá precedido por `LA`.

* Productos para vectores y matrices: `dot`, `vdot`, `inner`, `outer`, `matmul`, `tensordot`, `einsum`, `LA.matrix_power`, `kron`


* Descomposiciones: `LA.cholesky`, `LA.qr`, `LA.svd`


* Eigenvalores: `LA.eig`, `LA.eigh`, `LA.eigvals`, `LA.eigvalsh`


* Normas y otros números: `LA.norm`, `LA.cond`, `LA.det`, `LA.matrix_rank`, `LA.slogdet`, `trace`


* Resolución de ecuaciones e inversión de matrices: `LA.solve`, `LA.tensorsolve`, `LA.lstsq`, `LA.inv`, `LA.pinv`, `LA.tensorinv`


Dentro de `scipy` tenemos más cosas relacionadas.

In [ ]:
# juguemos un poco con ellas

## Manipulación de `ndarrays`

`tile`, `hstack`, `vstack`, `dstack`, `hsplit`, `vsplit`, `dsplit`, `repeat`, `reshape`, `ravel`, `resize`,...

In [ ]:
# juguemos un poco con ellas

## Módulos de interés dentro de `numpy`

Dentro de `numpy` podemos encontrar módulos para:

* Usar números aleatorios: `np.random`


* Usar FFT: `np.fft`


* Usar *masked arrays*: `np.ma`


* Usar polinomios: `np.polynomial`


* Usar álgebra lineal: `np.linalg`


* Usar matrices: `np.matlib`


* ...

Toda esta funcionalidad se puede ampliar y mejorar usando `scipy`.

## Cálculo matricial

In [ ]:
a1 = np.repeat(2, 9).reshape(3, 3)
a2 = np.tile(2, (3, 3))
a3 = np.ones((3, 3), dtype=np.int) * 2
print(a1)
print(a2)
print(a3)

In [ ]:
b = np.arange(1, 4)
print(b)

In [ ]:
print(a1.dot(b))
print(np.dot(a2, b))
print(a3 @ b)  # only python version >= 3.5

Lo anterior lo hemos hecho usando *ndarrays* pero `numpy` también ofrece una estructura de datos `matrix`.

In [ ]:
a_mat = np.matrix(a1)
a_mat

In [ ]:
b_mat = np.matrix(b)

In [ ]:
a_mat @ b_mat

In [ ]:
a_mat @ b_mat.T

Como vemos, con los *ndarrays* no hace falta que seamos rigurosos con las dimensiones, en cambio, si usamos `np.matrix` como tipos hemos de realizar operaciones matriciales válidas (por ejemplo, que las dimensiones sean correctas).

A efectos prácticos, en general, los *ndarrays* se pueden usar como `matrix` conociendo estas pequeñas cosas.